language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=firmware

install:
    - pip install -U platformio

script:
    - platformio ci --project-conf=firmware/platformio.ini
